kind: pipeline
name: build

platform:
  os: linux

steps:
- name: build
  image: plugins/docker:19
  settings:
    repo: ghcr.io/rkojedzinszky/thermo-center-controller
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
    mirror:
      from_secret: hub_docker_mirror

