kind: pipeline
name: build

platform:
  os: linux

steps:
- name: build
  image: plugins/docker
  settings:
    repo: ghcr.io/rkojedzinszky/thermo-center-controller
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true

