kind: pipeline
name: build

platform:
  os: linux

steps:
- name: build
  image: plugins/docker
  settings:
    repo: rkojedzinszky/thermo-center-controller
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true

