kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thermo-center-controller
subjects:
- kind: ServiceAccount
  name: thermo-center-controller
roleRef:
  kind: ClusterRole
  name: thermo-center-controller
  apiGroup: rbac.authorization.k8s.io
